apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: model-v2
spec:
  id: model-v2
  type: mock
  model: gpt-4o-mini-2024-12
  additional_config:
    mock_config: mock-responses-v2.yaml
  defaults:
    temperature: 0.0
    max_tokens: 64
    top_p: 1.0
