# yaml-language-server: $schema=../../../schemas/v1alpha1/provider.json
apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: openai-mini
spec:
  id: "openai-mini"
  type: openai
  model: gpt-4o-mini
