apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: mock-slow
spec:
  id: mock-slow
  type: mock
  model: mock-slow-1
  additional_config:
    mock_config: mock-responses-slow.yaml
  defaults:
    temperature: 0.1
    max_tokens: 256
    top_p: 1.0
