#!/usr/bin/env bash
#
# commit-msg hook for PromptArena
# Enforces the Developer Certificate of Origin (DCO): every commit must carry a
# "Signed-off-by:" trailer matching the commit author.
#
# The sign-off cannot be checked by the pre-commit hook because the commit
# message does not exist yet at pre-commit time — this is why DCO lives here,
# in commit-msg, which receives the message file as $1.
#
# To sign off automatically, commit with -s/--signoff:
#   git commit -s
# To fix the most recent commit:
#   git commit --amend -s --no-edit
#

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

MSG_FILE="$1"

# Skip merge commits — they are generated by git and follow DCO via their parents.
if git rev-parse -q --verify MERGE_HEAD >/dev/null 2>&1; then
    exit 0
fi

# Author identity for this commit (honours --author overrides and env vars).
AUTHOR_IDENT="$(git var GIT_AUTHOR_IDENT)"
# GIT_AUTHOR_IDENT looks like: "Name <email> 1700000000 +0000" — extract the email.
AUTHOR_EMAIL="${AUTHOR_IDENT#*<}"
AUTHOR_EMAIL="${AUTHOR_EMAIL%%>*}"

# Collect well-formed sign-off trailers, ignoring scissor/comment lines.
SIGNOFFS="$(grep -iE '^Signed-off-by: .+ <.+@.+>$' "$MSG_FILE" 2>/dev/null || true)"

if [ -z "$SIGNOFFS" ]; then
    echo -e "${RED}✗ Missing DCO sign-off${NC}" >&2
    echo "" >&2
    echo "Every commit must be signed off under the Developer Certificate of Origin." >&2
    echo "Add a sign-off trailer by committing with -s:" >&2
    echo "" >&2
    echo "    git commit -s" >&2
    echo "    git commit --amend -s --no-edit   # to fix this commit" >&2
    echo "" >&2
    echo "Expected trailer:" >&2
    echo "    Signed-off-by: $(git config user.name) <${AUTHOR_EMAIL}>" >&2
    exit 1
fi

# Require a sign-off whose email matches the commit author (mirrors the GitHub DCO check).
if ! grep -iqE "^Signed-off-by: .+ <${AUTHOR_EMAIL}>$" "$MSG_FILE"; then
    echo -e "${RED}✗ DCO sign-off does not match the commit author${NC}" >&2
    echo "" >&2
    echo "Author:   <${AUTHOR_EMAIL}>" >&2
    echo "Found:" >&2
    echo "$SIGNOFFS" | sed 's/^/    /' >&2
    echo "" >&2
    echo "Add a matching sign-off:" >&2
    echo "    git commit --amend -s --no-edit" >&2
    exit 1
fi

echo -e "${GREEN}✓${NC} DCO sign-off present"
exit 0
