// Package audio provides real-time audio monitoring for Arena duplex runs.
//
// # Observer model — read this before changing anything
//
// Audio in this package follows a strict observer model: this package
// exposes a fan-out bus (AudioRouter) whose subscribers (LocalSink, RMS
// level meters, SSE web playback, recording sinks) are read-only
// observers. They watch the audio flowing through the data path; they
// MUST NOT influence it.
//
// Cadence (the wall-clock rate at which audio chunks advance through
// the pipeline) is owned by exactly one place — the
// runtime/pipeline/stage.AudioPacingStage on the data path itself.
// Everything in this package is downstream of that cadence authority
// and is forbidden from feeding rate signals back to it. Specifically:
//
//   - Router.Publish drops on full intake. It does not block.
//   - Router fan-out drops per-consumer on full inbox. It does not block.
//   - LocalSink.Push drops on full sink buffer. It does not block.
//
// Drop-on-full is load-bearing, not a wart. If you change any of these
// to block, you create a backchannel from a UI/observer surface into
// the producer pipeline — and via the input branch's broadcast, into
// the LLM provider's session. The provider's VAD timestamps arrival
// cadence to time turn-end silence, so warping that cadence based on
// "is anyone listening locally" produces wrong turn boundaries. Two
// other reasons block-on-full doesn't work even before that:
//
//  1. Many parallel runs typically execute headlessly with no LocalSink
//     attached at all. Sink-driven backpressure can't be the model
//     when most runs have no sink to be back-pressured by.
//  2. Even when a sink is attached, the operator may switch which run
//     they're listening to — a run's correctness can't depend on
//     whether someone happens to be tuned in.
//
// If you need cadence enforcement somewhere, the answer is another
// AudioPacingStage instance on the data path, not "make the sink
// blocking."
//
// # Lifecycle
//
// Per-run. Each scenario run gets its own AudioRouter goroutine,
// started when MonitorTap is constructed and stopped at run completion.
//
// # Flow
//
// Audio chunks flow from the duplex provider stage through MonitorTap
// into the router, which fans out to per-consumer bounded channels.
// Slow consumers drop their own frames; the router and other consumers
// keep flowing.
package audio

import "time"

// MonitorMode controls when audio monitoring is active.
type MonitorMode string

const (
	// ModeAuto enables monitoring when a TTY is attached and a duplex
	// scenario is running, unless --ci is set.
	ModeAuto MonitorMode = "auto"
	// ModeOn forces monitoring on regardless of TTY/CI state.
	ModeOn MonitorMode = "on"
	// ModeOff disables monitoring; MonitorTap is not added to the pipeline.
	ModeOff MonitorMode = "off"
)

// Direction identifies whether audio came from the user (input) or the
// agent (output).
type Direction string

const (
	// DirectionInput is audio captured from the user / synthetic caller.
	DirectionInput Direction = "input"
	// DirectionOutput is audio generated by the agent.
	DirectionOutput Direction = "output"
)

// Frame is the canonical audio chunk format used inside the router.
// Samples are mono s16le at the canonical rate (configured per-run).
type Frame struct {
	Direction Direction
	Samples   []int16
	Timestamp time.Time
}

// RMSFrame is emitted at ~30 Hz for level meter consumers (TUI, browser).
// Levels are normalized 0.0-1.0 RMS over a rolling ~50 ms window.
type RMSFrame struct {
	UserLevel  float32
	AgentLevel float32
	Timestamp  time.Time
}

// Canonical sample rates supported by the router.
const (
	// Rate16k is the 16 kHz canonical rate.
	Rate16k = 16000
	// Rate24k is the 24 kHz canonical rate (default).
	Rate24k = 24000
	// Rate48k is the 48 kHz canonical rate.
	Rate48k = 48000
)

// Options configures the audio monitoring stack at engine startup.
type Options struct {
	// Mode controls when the MonitorTap is added to the pipeline.
	Mode MonitorMode
	// Rate is the canonical sample rate inside the router. Must be one
	// of Rate16k, Rate24k, or Rate48k.
	Rate int
	// LocalSink enables oto-backed local playback when monitoring is on.
	LocalSink bool
	// SSEPlayback enables the web SSE relay subscription.
	SSEPlayback bool
	// LevelMeter enables the RMSFrame channel for TUI consumption.
	LevelMeter bool
}

// DefaultOptions returns sensible defaults: auto mode, 24 kHz, all surfaces enabled.
func DefaultOptions() Options {
	return Options{
		Mode:        ModeAuto,
		Rate:        Rate24k,
		LocalSink:   true,
		SSEPlayback: true,
		LevelMeter:  true,
	}
}

// ValidRates lists the canonical rates accepted by the router.
var ValidRates = []int{Rate16k, Rate24k, Rate48k}

// IsValidRate returns whether the given rate is a supported canonical rate.
func IsValidRate(rate int) bool {
	for _, r := range ValidRates {
		if r == rate {
			return true
		}
	}
	return false
}
