package engine

import (
	"time"

	"github.com/AltairaLabs/PromptKit/runtime/types"
	"github.com/AltairaLabs/PromptKit/tools/arena/assertions"
	"github.com/AltairaLabs/PromptKit/tools/arena/statestore"
)

// RunPlan defines the test execution plan
type RunPlan struct {
	Combinations []RunCombination
}

// RunCombination represents a single test execution
type RunCombination struct {
	Region       string
	ScenarioID   string // For scenario-based runs
	EvalID       string // For eval-based runs (mutually exclusive with ScenarioID)
	ProviderID   string // Not used for eval runs (provider comes from recording)
	RecordingRef string // For batch evals: specific recording reference ID (resolved by adapter)
}

// RunResult contains the complete results of a single test execution
type RunResult struct {
	RunID      string                  `json:"RunID"`
	PromptPack string                  `json:"PromptPack"`
	Region     string                  `json:"Region"`
	ScenarioID string                  `json:"ScenarioID"`
	ProviderID string                  `json:"ProviderID"`
	Params     map[string]interface{}  `json:"Params"`
	Messages   []types.Message         `json:"Messages"`
	Commit     map[string]interface{}  `json:"Commit"`
	Cost       types.CostInfo          `json:"Cost"`
	ToolStats  *types.ToolStats        `json:"ToolStats"`
	Violations []types.ValidationError `json:"Violations"`
	StartTime  time.Time               `json:"StartTime"`
	EndTime    time.Time               `json:"EndTime"`
	Duration   time.Duration           `json:"Duration"`
	Error      string                  `json:"Error"`
	SelfPlay   bool                    `json:"SelfPlay"`
	PersonaID  string                  `json:"PersonaID"`

	UserFeedback  *statestore.Feedback `json:"UserFeedback"`
	SessionTags   []string             `json:"SessionTags"`
	AssistantRole *SelfPlayRoleInfo    `json:"AssistantRole"`
	UserRole      *SelfPlayRoleInfo    `json:"UserRole"`

	// Media outputs generated by LLMs during test execution
	MediaOutputs []MediaOutput `json:"MediaOutputs,omitempty"`

	// Session recording path (if recording was enabled)
	RecordingPath string `json:"RecordingPath,omitempty"`

	// Conversation-level assertions evaluated after the conversation completes (summary format)
	ConversationAssertions AssertionsSummary `json:"conversation_assertions,omitempty"`

	// A2A agent metadata (populated from config for report rendering)
	A2AAgents []A2AAgentInfo `json:"A2AAgents,omitempty"`

	// TrialResults holds aggregated statistics when a scenario is run with Trials > 1.
	TrialResults *TrialResults `json:"trial_results,omitempty"`
}

// AssertionsSummary matches the structure used for turn-level assertions in message meta
type AssertionsSummary struct {
	Failed  int                                       `json:"failed"`
	Passed  bool                                      `json:"passed"`
	Results []assertions.ConversationValidationResult `json:"results"`
	Total   int                                       `json:"total"`
}

// TrialResults holds aggregated results from multiple trial executions of a scenario.
type TrialResults struct {
	// TrialCount is the number of trials executed.
	TrialCount int `json:"trial_count"`
	// PassRate is the fraction of trials where all assertions passed (0.0-1.0).
	PassRate float64 `json:"pass_rate"`
	// FlakinessScore ranges from 0 (deterministic) to 1 (maximally flaky, 50/50).
	FlakinessScore float64 `json:"flakiness_score"`
	// PerAssertionStats maps assertion ID to its pass rate across trials.
	PerAssertionStats map[string]AssertionTrialStats `json:"per_assertion_stats,omitempty"`
}

// AssertionTrialStats holds per-assertion statistics across trial runs.
type AssertionTrialStats struct {
	// PassRate is the fraction of trials where this assertion passed.
	PassRate float64 `json:"pass_rate"`
	// PassCount is the number of trials where this assertion passed.
	PassCount int `json:"pass_count"`
	// FailCount is the number of trials where this assertion failed.
	FailCount int `json:"fail_count"`
	// FlakinessScore for this specific assertion.
	FlakinessScore float64 `json:"flakiness_score"`
}

// MediaOutput represents media content generated by an LLM during test execution
type MediaOutput struct {
	Type       string `json:"type"`                // "image", "audio", "video"
	MIMEType   string `json:"mime_type"`           // e.g., "image/jpeg", "audio/mp3"
	SizeBytes  int64  `json:"size_bytes"`          // Size of the media file
	Duration   *int   `json:"duration,omitempty"`  // Duration in seconds (for audio/video)
	Width      *int   `json:"width,omitempty"`     // Width in pixels (for image/video)
	Height     *int   `json:"height,omitempty"`    // Height in pixels (for image/video)
	FilePath   string `json:"file_path,omitempty"` // Path where media was saved
	Thumbnail  string `json:"thumbnail,omitempty"` // Base64-encoded thumbnail for HTML reports
	MessageIdx int    `json:"message_index"`       // Index of message containing this media
	PartIdx    int    `json:"part_index"`          // Index of content part within the message
}

// SelfPlayRoleInfo contains provider information for self-play roles
type SelfPlayRoleInfo struct {
	Provider string
	Model    string
	Region   string
}

// A2AAgentInfo contains metadata about an A2A agent for report rendering.
type A2AAgentInfo struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Skills      []A2ASkillInfo `json:"skills,omitempty"`
}

// A2ASkillInfo contains metadata about a single A2A agent skill.
type A2ASkillInfo struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}
