package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/AltairaLabs/PromptKit/pkg/config"
)

var deployCmd = &cobra.Command{
	Use:   "deploy",
	Short: "Deploy the arena pack to a target environment",
	Long: `Deploy the arena pack to a target environment using a deploy adapter.

When run without a subcommand, deploy executes a plan followed by apply.

Subcommands:
  plan      Preview what would be deployed
  apply     Apply the deployment
  status    Show current deployment status
  destroy   Tear down a deployment

Examples:
  promptarena deploy --env production
  promptarena deploy plan --env staging
  promptarena deploy apply --env staging
  promptarena deploy status --env production
  promptarena deploy destroy --env staging`,
	RunE: runDeploy,
}

var (
	deployEnv    string
	deployConfig string
)

func init() {
	rootCmd.AddCommand(deployCmd)

	deployCmd.PersistentFlags().StringVarP(&deployEnv, "env", "e", "", "Target environment")
	deployCmd.PersistentFlags().StringVar(&deployConfig, "config", "arena.yaml", "Config file path")

	deployCmd.AddCommand(deployPlanCmd)
	deployCmd.AddCommand(deployApplyCmd)
	deployCmd.AddCommand(deployStatusCmd)
	deployCmd.AddCommand(deployDestroyCmd)
}

// loadDeployConfig loads the arena config and returns the deploy section.
// Returns an error if the config file is missing or has no deploy configuration.
func loadDeployConfig() (*config.DeployConfig, error) {
	if _, err := os.Stat(deployConfig); os.IsNotExist(err) {
		return nil, fmt.Errorf("config file not found: %s", deployConfig)
	}

	cfg, err := config.LoadConfig(deployConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to load config: %w", err)
	}

	if cfg.Deploy == nil {
		return nil, fmt.Errorf(
			"no deploy configuration found in %s\nAdd a 'deploy' section to your arena config",
			deployConfig,
		)
	}

	return cfg.Deploy, nil
}

const defaultEnvironment = "default"

// resolveEnvironment returns the target environment name, falling back to "default" if not specified.
func resolveEnvironment() string {
	if deployEnv != "" {
		return deployEnv
	}
	return defaultEnvironment
}

// runDeploy executes plan + apply when no subcommand is given.
func runDeploy(cmd *cobra.Command, args []string) error {
	deployCfg, err := loadDeployConfig()
	if err != nil {
		return err
	}

	env := resolveEnvironment()

	fmt.Printf("Deploying with provider %q to environment %q\n", deployCfg.Provider, env)
	fmt.Println()
	fmt.Println("Step 1: Planning deployment...")
	fmt.Printf("  Config file: %s\n", deployConfig)
	fmt.Printf("  Provider:    %s\n", deployCfg.Provider)
	fmt.Printf("  Environment: %s\n", env)
	fmt.Println()
	fmt.Println("Step 2: Applying deployment...")
	fmt.Println()
	fmt.Println("[stub] Deploy adapter not yet implemented." +
		" This command will execute plan + apply once the adapter manager is available.")

	return nil
}

// --- deploy plan ---

var deployPlanCmd = &cobra.Command{
	Use:   "plan",
	Short: "Preview the deployment plan",
	Long: `Show what resources would be created, updated, or destroyed
without making any changes.

Examples:
  promptarena deploy plan --env staging
  promptarena deploy plan --config custom.yaml`,
	RunE: runDeployPlan,
}

func runDeployPlan(cmd *cobra.Command, args []string) error {
	deployCfg, err := loadDeployConfig()
	if err != nil {
		return err
	}

	env := resolveEnvironment()

	fmt.Printf("Deploy plan for environment: %s (provider: %s)\n", env, deployCfg.Provider)
	fmt.Printf("  Config file: %s\n", deployConfig)
	fmt.Println()

	if envCfg, ok := deployCfg.Environments[env]; ok && envCfg != nil {
		fmt.Printf("  Environment-specific config keys: %d\n", len(envCfg.Config))
	} else if env != defaultEnvironment {
		fmt.Printf("  Note: no environment-specific overrides for %q\n", env)
	}

	fmt.Println()
	fmt.Println("[stub] Plan output will be generated by the deploy adapter once implemented.")

	return nil
}

// --- deploy apply ---

var deployApplyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Apply the deployment",
	Long: `Apply the deployment plan to the target environment.
This creates or updates resources as needed.

Examples:
  promptarena deploy apply --env staging
  promptarena deploy apply --env production --config custom.yaml`,
	RunE: runDeployApply,
}

func runDeployApply(cmd *cobra.Command, args []string) error {
	deployCfg, err := loadDeployConfig()
	if err != nil {
		return err
	}

	env := resolveEnvironment()

	fmt.Printf("Applying deployment to environment: %s (provider: %s)\n", env, deployCfg.Provider)
	fmt.Printf("  Config file: %s\n", deployConfig)
	fmt.Println()
	fmt.Println("[stub] Apply will be executed by the deploy adapter once implemented.")

	return nil
}

// --- deploy status ---

var deployStatusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show deployment status",
	Long: `Show the current status of a deployment in the target environment.

Examples:
  promptarena deploy status --env production
  promptarena deploy status --env staging`,
	RunE: runDeployStatus,
}

func runDeployStatus(cmd *cobra.Command, args []string) error {
	deployCfg, err := loadDeployConfig()
	if err != nil {
		return err
	}

	env := resolveEnvironment()

	fmt.Printf("Deployment status for environment: %s (provider: %s)\n", env, deployCfg.Provider)
	fmt.Printf("  Config file: %s\n", deployConfig)
	fmt.Println()
	fmt.Println("[stub] Status will be reported by the deploy adapter once implemented.")

	return nil
}

// --- deploy destroy ---

var deployDestroyCmd = &cobra.Command{
	Use:   "destroy",
	Short: "Tear down a deployment",
	Long: `Destroy all resources associated with a deployment in the target environment.

This is a destructive operation. Use with caution.

Examples:
  promptarena deploy destroy --env staging
  promptarena deploy destroy --env production`,
	RunE: runDeployDestroy,
}

func runDeployDestroy(cmd *cobra.Command, args []string) error {
	deployCfg, err := loadDeployConfig()
	if err != nil {
		return err
	}

	env := resolveEnvironment()

	fmt.Printf("Destroying deployment in environment: %s (provider: %s)\n", env, deployCfg.Provider)
	fmt.Printf("  Config file: %s\n", deployConfig)
	fmt.Println()
	fmt.Println("[stub] Destroy will be executed by the deploy adapter once implemented.")

	return nil
}
